### ISSUE TITLE
Unity.ResolutionFailedException: RestSharp.Athuenticators.IAuthenticator, is an interface....Are you missing a type mapping?

### ISSUE THREAD

**Issue by 48x16** [AutomateThePlanet/BELLATRIX#16]
Taken from Master code 29/03/22

Within the ApiClientService.cs class:

`var authenticator = ServicesCollection.Current.Resolve<IAuthenticator>(); `

Triggers the following exception against any test (TableWithHeader_GetItems) for example:

Unity.ResolutionFailedException
  HResult=0x80131500
  Message=The current type, RestSharp.Authenticators.IAuthenticator, is an interface and cannot be constructed. Are you missing a type mapping?
_____________________________________________________
Exception occurred while:

• while resolving:  IAuthenticator

  Source=Unity.Container
  StackTrace:
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides)
   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at Bellatrix.ServicesCollection.Resolve[T](Boolean shouldThrowResolveException) in C:\BELLATRIX-master\src\Bellatrix.Core\infrastructure\ioc\ServicesCollection.cs:line 120

Inner Exception 1:
InvalidOperationException: The current type, RestSharp.Authenticators.IAuthenticator, is an interface and cannot be constructed. Are you missing a type mapping?

Inner Exception 2:
InvalidRegistrationException: Exception of type 'Unity.Exceptions.InvalidRegistrationException' was thrown.

I currently don't have a fix, but will continue reading up on it. The .cs file contains an interesting TODO: // TODO: is this going to be accessible in the service container?

Thanks again,
Rich

**Comment by angelovstanton** [comment]
Have you tried using the authentication attributes since this is how this is supposed to work? If I remember correctly there is a special plugin in the API project that takes care of this.

**Comment by 48x16** [comment]
Hi,

I may need a bit more guidance from you (sorry!). For a web test, I have stepped through the code, and this method is returning null during initialisation. 

`        private IAuthenticator GetAuthenticatorByType(Type currentType)
        {
            if (currentType == null)
            {
                throw new ArgumentNullException();
            }
            var authenticationClassAttribute = currentType.GetCustomAttribute<AuthenticationStrategyAttribute>(true);
            return authenticationClassAttribute?.GetAuthenticator();
        } `


I'm not sure what attributes to set? 

AuthenticationStrategyAttribute.cs contains the only attributes I can find around authentication.

`  [AttributeUsage(AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
    public abstract class AuthenticationStrategyAttribute : Attribute
    {
        public abstract IAuthenticator GetAuthenticator();
    }`

Appreciate any time you have plus any guidance on this. I'm failing to grasp the issue! 

Thanks again,
Rich

**Comment by angelovstanton** [comment]
Please check the following doc - https://docs.bellatrix.solutions/api-automation/authentication/

**Comment by 48x16** [comment]
I've applied [HttpBasicAuthenticationStrategy("Test", "Test")] to the TestClass and that has resolved the GetAuthenticatorByType but hasn't resolved the original issue:

Within the ApiClientService.cs class:

var authenticator = ServicesCollection.Current.Resolve<IAuthenticator>();

That remains null.

**Comment by angelovstanton** [comment]
Maybe there is a bug. To be honest I haven't use these authenticator in practice. You need to debug the plugin responsible for adding them. Search where they are used and debug the code. Not sure when I will have the time to debug it myself.

**Comment by 48x16** [comment]
I wasn't planning on using the authenticator either. 

But App.cs is being called as part of the WebTest.cs initialisation, which has in it's constructor _apiClientService = GetNewApiClientService(), which in turn calls the ApiClientService method that attempts to resolve the IAuthenticator and fires the exception. 

Is there a reason that the web and api are coupled together? Or is there a way I can turn off the API part completely for now as i'm only testing a web front end in this instance?

Rich

**Comment by angelovstanton** [comment]
hm this shouldn't happen. I mean we use the API like this in many projects. Especially in web projects since there we use it to set up data via APIs.

**Comment by angelovstanton** [comment]
is this happening when you run web getting started tests or this is happening only for your custom project?

**Comment by angelovstanton** [comment]
I mean when you run all of the Web Getting Started Guide tests are they all green? I am asking since the project is properly configured. My theory is that it is possible to miss some configuration and due to this to receive this error.

**Comment by 48x16** [comment]
That's correct, this is out of the box, they all pass first time through, but if you run the test again the exceptions appear.

All i've changed is updated the edge driver through nuget.

**Comment by angelovstanton** [comment]
So, in order to reproduce the problem, I need to run all web getting started tests twice?

**Comment by 48x16** [comment]
Nope, just 1 web test twice (e.g. Table_GetItems)

**Comment by angelovstanton** [comment]
https://user-images.githubusercontent.com/7361065/161256712-d2a677cd-6305-4822-8dc4-57f2cc513536.mp4

I tried to reproduce it but with the latest version on master branch I cannot.

**Comment by 48x16** [comment]
You aren't debugging it. Add a breakpoint at the end of the test, and run it in debug.

**Comment by angelovstanton** [comment]
https://user-images.githubusercontent.com/7361065/161259419-b7043a48-36f5-4fcf-b402-fce5b1c6104d.mp4

Same result.

**Comment by 48x16** [comment]
And in your events? (Sorry about this!).

![image](https://user-images.githubusercontent.com/37348105/161266332-b94ba4ce-da85-417b-84f7-960005ba07ad.png)

**Comment by angelovstanton** [comment]
This happens inside the ApiClientService class but when if you open the resolve method from where this error comes from it is ignored which is the expected behavior
![image](https://user-images.githubusercontent.com/7361065/161266994-7e4005ce-8a1b-46a6-954b-c41de98c70fe.png)

**Comment by angelovstanton** [comment]
As I explained the registration of the this interface happens through ApiAuthenticationWorkflowPlugin which is based on the authentication attributes

**Comment by 48x16** [comment]
Ok that's fine then if it's expected. Even with [SimpleAuthenticationStrategy("s","d","f","f")] at the top of my test class I still see this exception, which is also fine? 

I owe you about 3 beers for explaining this. So thanks again for helping me.

**Comment by 48x16** [comment]
And just for info, when I run my own tests against a website I end up with the following:

![image](https://user-images.githubusercontent.com/37348105/161272751-108922cd-e2d0-4a32-af0e-889f73d1c527.png)

![image](https://user-images.githubusercontent.com/37348105/161272836-bd6a2ccc-dafa-424b-90c0-d38c7f1258f9.png)

Which makes me think something is failing a lot, whether this is the case or not, as watching the test it passes.

**Comment by angelovstanton** [comment]
probably something is wrong, I guess you need to debug the ServiceContainer and see what is going on.

**Comment by 48x16** [comment]
Not sure why this line is here when the code checks if it's registered straight afterwards? What if it doesn't exist to start with?

![image](https://user-images.githubusercontent.com/37348105/161285572-f3bd0ff8-256e-46f7-a8cf-dafebb256ba6.png)

If I comment it out I get rid of the exception IAuthenticator post test initialisation (My kind of fix :))

--------------------------------------------------------------
I have also added the following in ShutdownBrowser to stop it disposing of a non existent previous browser:

![image](https://user-images.githubusercontent.com/37348105/161291567-d2625e4e-55fd-453e-9d85-fb53fa57b0b0.png)

That removes another Exception.

--------------------------------------------------------------
Then in the UnregisterSingleInstance I get the exceptions triggered around:

System.IO.IOExcpetion in System.Net.Sockets.dll
System.Net.Http.dll
System.Private.CoreLib.dll

I assume this is on test clean up, but I can look into these next week.

Not sure if any of these 'fixes' are helpful to your codebase! 

But thanks again for all your help this week.
Rich

**Comment by angelovstanton** [comment]
perfect. Those seems like legit fixes on first look. :) Thank you!
