### ISSUE TITLE
Implement capability to add sections to testFrameworkSettings

### ISSUE THREAD

**Issue by Armz10** [AutomateThePlanet/BELLATRIX#18]
It would be great to be able to add your own sections into the testFrameworkSettings JSON file. 

For example,
```
"credentialSettings": {
    "email": "user@domain.com",
    "password": "Password",
  }
```

**Comment by angelovstanton** [comment]
Hi, actually you can add custom sections to the config this is not a problem. Check this article: https://www.automatetheplanet.com/enterprise-test-automation-framework-configuration-module-design/
