### ISSUE TITLE
Bellatrix License error in macOS

### ISSUE THREAD

**Issue by JeriYasmin** [AutomateThePlanet/BELLATRIX#2]
I couldn't run Bellatrix projects in mac machine. I am getting the following error. 

"The BELLATRIX license was created on a different machine. Please try to reactivate the license."

The projects are created in different machine and checked into Repo. When I clone the repo and run I get the above message. 
<img width="1440" alt="Screen Shot 2021-06-10 at 9 30 39 am" src="https://user-images.githubusercontent.com/85652634/121442929-e9089880-c9cf-11eb-87e8-5ff967bbe616.png">

Tried following things:
1) Removed all the nuget pacages and added again accepting the licenses.
2) Created a new project template in Windows machine, copied the project in mac machine and tried to run

**Comment by angelovstanton** [comment]
Hi! You don't need any NuGet packages. You just need to clone the official repo and start coding there. The old NuGet packages are not longer supported and are from the era where the tool was paid and closed-sourced.
