### ISSUE TITLE
Error OpenQA.Selenium.WebDriverTimeoutException is received when running UI tests very often

### ISSUE THREAD

**Issue by StaEft** [AutomateThePlanet/BELLATRIX#22]
Since the start of the last week I`ve started to receive error when I run UI tests.

`OneTimeSetUp: OpenQA.Selenium.WebDriverTimeoutException : timeout: Timed out receiving message from renderer:`

The error appears after the Url for the login page is requested. After that the page is not loaded. The test fails with this error, that looks like an issue with the WebDriver. There is a strange behavior that sometimes after I restart the PC or VS, the  test runs several times successfully and than starts to fail again. Also, the same test works without problems on other PCs.  I`ve tried different ways to solve the issue - update Windows, Update VS, Re-install/update of the browser /Chrome/, etc.

Has someone else hit a problem of that kind? Do you think that this is related to Bellatrix or to the WebDriver?

**Comment by angelovstanton** [comment]
Hi,
My guess is that this happened because of new version of a browser. You can check what happens if you change the browser. Before doing that. Yesterday, we have just released the latest version of BELLATRIX with latest version of Selenium which was released 2-3 days ago. So, you can just get the new version first and try with it.

**Comment by StaEft** [comment]
Thank you for the quick response. I will try your suggestions and I will let you know the result.

**Comment by StaEft** [comment]
Hi, again. Unfortunately, the update to the latest version of Bellatrix, did not help. After some more researches and try outs I found out that the problem might be caused by my internet connection. While on WiFi the error appears, however once I've switched to cable the error is not present anymore. Might have to do something with the VPN filtering the WiFi connection.
