### ISSUE TITLE
Button.Click() method doesn't throw an exception, when the element is not found

### ISSUE THREAD

**Issue by kristiana-borisova** [AutomateThePlanet/BELLATRIX#7]
https://github.com/AutomateThePlanet/BELLATRIX/blob/a64d8ffeeb6ffa11540b0d0b7cce3d3536f56fa4/src/Bellatrix.Web/services/JavaScriptService.cs#L44

When Execute method timeout because the component is not found, it doesn't throw an exception. Instead it returns empty string and the test proceeds without indicating that the component was not found.

**Comment by kristiana-borisova** [comment]
[TestFixture]
    [Browser(BrowserType.Chrome, Lifecycle.ReuseIfStarted)]
    public class LoginAbv : WebTest
    {
        [Test]
        public void LoginToAbv()
        {
            App.Navigation.Navigate("http://demos.bellatrix.solutions/my-account/");
            App.Components.CreateById<Button>("loginBut").Click();
        }
    }

Although the button was not found, the test passes.

**Comment by angelovstanton** [comment]
Since everything is open source I suggest you to open the Click method and find the code where the framework actually clicks and debug it and see whether this is the real problem. I don't think that there is a different behavior for buttons compared to TestFields. It is possible that the element is found and clicked but for some reason the app not to respond properly don't know. We use the framework in enterprise projects with more than 10k+ tests and I haven't seen such behaviour. 
I am asking you to do the debugging because for obvious reasons I cannot do it. :)

**Comment by angelovstanton** [comment]
This is the current internal implementation:

 internal void Click(EventHandler<ComponentActionEventArgs> clicking, EventHandler<ComponentActionEventArgs> clicked)
        {
            clicking?.Invoke(this, new ComponentActionEventArgs(this));

            var sleepInterval = ConfigurationService.GetSection<WebSettings>().TimeoutSettings.SleepInterval;
            var timeout = ConfigurationService.GetSection<WebSettings>().TimeoutSettings.ElementToBeClickableTimeout;
            var timeoutTimeSpan = TimeSpan.FromSeconds(timeout);
            var sleepIntervalTimeSpan = TimeSpan.FromSeconds(sleepInterval);
            var wait = new WebDriverWait(new SystemClock(), WrappedDriver, timeoutTimeSpan, sleepIntervalTimeSpan);
            wait.IgnoreExceptionTypes(typeof(NoSuchElementException));

            try
            {
                wait.Until((s) =>
                {
                    try
                    {
                        this.ToExists().ToBeClickable().WaitToBe();
                        WrappedElement.Click();
                        return true;
                    }
                    catch (ElementNotInteractableException e)
                    {
                        return false;
                    }
                    catch (WebDriverTimeoutException e)
                    {
                        return false;
                    }
                    catch (Exception e)
                    {
                        return false;
                    }
                });
            }
            catch (Exception e)
            {
                JavaScriptService.Execute("arguments[0].focus();arguments[0].click();", this);
            }

            clicked?.Invoke(this, new ComponentActionEventArgs(this));
        }

What fix do you suggest?

**Comment by angelovstanton** [comment]
This is the current internal implementation:

` internal void Click(EventHandler<ComponentActionEventArgs> clicking, EventHandler<ComponentActionEventArgs> clicked)
        {
            clicking?.Invoke(this, new ComponentActionEventArgs(this));

            var sleepInterval = ConfigurationService.GetSection<WebSettings>().TimeoutSettings.SleepInterval;
            var timeout = ConfigurationService.GetSection<WebSettings>().TimeoutSettings.ElementToBeClickableTimeout;
            var timeoutTimeSpan = TimeSpan.FromSeconds(timeout);
            var sleepIntervalTimeSpan = TimeSpan.FromSeconds(sleepInterval);
            var wait = new WebDriverWait(new SystemClock(), WrappedDriver, timeoutTimeSpan, sleepIntervalTimeSpan);
            wait.IgnoreExceptionTypes(typeof(NoSuchElementException));

            try
            {
                wait.Until((s) =>
                {
                    try
                    {
                        this.ToExists().ToBeClickable().WaitToBe();
                        WrappedElement.Click();
                        return true;
                    }
                    catch (ElementNotInteractableException e)
                    {
                        return false;
                    }
                    catch (WebDriverTimeoutException e)
                    {
                        return false;
                    }
                    catch (Exception e)
                    {
                        return false;
                    }
                });
            }
            catch (Exception e)
            {
                JavaScriptService.Execute("arguments[0].focus();arguments[0].click();", this);
            }

            clicked?.Invoke(this, new ComponentActionEventArgs(this));
        }`

What fix do you suggest?

**Comment by kristiana-borisova** [comment]
I debugged it, that's why I wrote the issue.
SetText() catch the exception and throws it, using Component.GetAndWaitWebDriverElement():

```
            catch (WebDriverTimeoutException)
            {
                throw new TimeoutException($"\n\nThe element: \n Name: '{ComponentName}', \n Locator: '{LocatorType.Name} = {LocatorValue}', \n Type: '{ComponentType.Name}' \nWas not found on the page or didn't fulfill the specified conditions.\n\n");
            }
```

While in Click() method the exception is caught and logged into the console with JavaScriptService.Execute(), but the execution of the test continues:

```
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                return string.Empty;
            }
```

Is this done on purpose?

**Comment by angelovstanton** [comment]
I discuss it with my colleagues and it seems they spot the same problem and made a fix. It is already deployed on main branch.

this is the new code:

   internal void Click(EventHandler<ComponentActionEventArgs> clicking, EventHandler<ComponentActionEventArgs> clicked)
        {
            clicking?.Invoke(this, new ComponentActionEventArgs(this));

            var sleepInterval = ConfigurationService.GetSection<WebSettings>().TimeoutSettings.SleepInterval;
            var timeout = ConfigurationService.GetSection<WebSettings>().TimeoutSettings.ElementToBeClickableTimeout;
            var timeoutTimeSpan = TimeSpan.FromSeconds(timeout);
            var sleepIntervalTimeSpan = TimeSpan.FromSeconds(sleepInterval);
            var wait = new WebDriverWait(new SystemClock(), WrappedDriver, timeoutTimeSpan, sleepIntervalTimeSpan);
            wait.IgnoreExceptionTypes(typeof(NoSuchElementException));

            wait.Until((s) =>
            {
                try
                {
                    this.ToExists().ToBeClickable().WaitToBe();
                    WrappedElement.Click();
                    return true;
                }
                catch (ElementClickInterceptedException e)
                {
                    PerformJsClick();
                    return true;
                }
                catch (ElementNotInteractableException e)
                {
                    return false;
                }
                catch (WebDriverTimeoutException e)
                {
                    return false;
                }
                catch (Exception e)
                {
                    return false;
                }
            });

            clicked?.Invoke(this, new ComponentActionEventArgs(this));
        }

        private void PerformJsClick() => JavaScriptService.Execute("arguments[0].focus();arguments[0].click();", this);
