### ISSUE TITLE
A winapp driver can not attach to a process that has a long start time.

### ISSUE THREAD

**Issue by acrigney** [AutomateThePlanet/BELLATRIX#8]
Our application can probably take up to the 50 second win app driver limit to start so can Bellatrix work around this with configuration? Or should I make a code change to start our application first, our application also has a splash screen, I think you can handle that I read in the documentation but I can't find it now.
The work arounds that people have tried are here
https://github.com/microsoft/WinAppDriver/issues/1181

**Comment by angelovstanton** [comment]
You can specify custom arguments like the one mentioned on the WinAppDriver repo in the execution config under arguments array:

` "executionSettings": {
      "defaultLifeCycle": "restart every time",
      "shouldStartLocalService": "false",
      "resolution": "",
      "defaultAppPath": "AssemblyFolder\\Demos\\Wpf\\WPFSampleApp.exe",
      "url": "http://127.0.0.1:4722",
      "arguments": [
        {
          //"name": "{runName}",
          //"videoName": "{runName}.{timestamp}.mp4",
          //"logName": "{runName}.{timestamp}.log",
          //"enableVNC": "true",
          //"enableVideo": "true",
          //"enableLog": "true"
        }
      ]
    }
  },`
